services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/reproducibility_inspector_setup:latest
    command: make
    environment:
      DO_PAT: $DO_PAT
    volumes:
      - ${HOME}/.ssh/id_rsa:/root/.ssh/id_rsa
