---
- name: Install software using package managers
  hosts: inspector
  tasks:
    - name: Update system
      ansible.builtin.apt:
        update_cache: true
      become: true
    - name: Install cURL
      ansible.builtin.apt:
        name: "curl"
        state: present
      become: true
    - name: Install Docker
      ansible.builtin.apt:
        name: "docker.io"
        state: present
      become: true
    - name: Install Docker-compose
      ansible.builtin.apt:
        name: "docker-compose"
        state: present
      become: true
    - name: Install Git
      ansible.builtin.apt:
        name: "git"
        state: present
      become: true
    - name: Install Make
      ansible.builtin.apt:
        name: "make"
        state: present
      become: true
    - name: Install pip
      ansible.builtin.apt:
        name: "python3-pip"
        state: present
      become: true
    - name: Install pipx
      ansible.builtin.apt:
        name: "pipx"
        state: present
      become: true
    - name: Install Docker SDK for Python
      community.general.pipx:
        name: docker
        install_deps: true
      notify: Restart server
    - name: Add to docker group '{{ ansible_user_id }}'
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true
      become: true
      notify: Restart server
  handlers:
    - name: Restart server
      ansible.builtin.reboot:
      become: true

- name: Set system up
  hosts: inspector
  tasks:
    - name: Set time zone
      community.general.timezone:
        name: America/Los_Angeles
      become: true

- name: Run Inspector container
  hosts: inspector
  tasks:
    - name: Create work directory for geci-testmake
      ansible.builtin.file:
        path: /home/ciencia_datos/.testmake
        state: directory
        recurse: true
        owner: ciencia_datos
        group: ciencia_datos
    - name: Copy SSH keys
      ansible.builtin.copy:
        src: /root/.ssh/id_rsa
        dest: /home/ciencia_datos/.ssh/id_rsa
        mode: '0600'
    - name: Copy secrets
      ansible.builtin.copy:
        src: /root/.vault/
        dest: /home/ciencia_datos/.vault/
        mode: '0600'
    - name: Start the container
      community.docker.docker_container:
        name: reproducibility_inspector
        image: islasgeci/reproducibility_inspector:latest
        state: started
        restart_policy: "always"
        detach: true
        volumes:
          - /home/ciencia_datos/.testmake:/home/ciencia_datos/.testmake
          - /home/ciencia_datos/.vault/.secrets:/home/ciencia_datos/.vault/.secrets
          - /home/ciencia_datos/.ssh/id_rsa:/root/.ssh/id_rsa
          - /var/run/docker.sock:/var/run/docker.sock
